### PR TITLE
Add -p to man mput

### PR DESCRIPTION
**Pull request by andrewh1978**

### CODE REVIEW

**Comment by davepacheco** [comment]
This needs to be updated in both the source file and the generated manual page (which is built using "make manpages").  It would also be good to update CHANGES.md with the entry for this change.

**Comment by davepacheco** [comment]
When I run "make manpages", I get very different output for man/man1/mput.1.  I also see that behavior on master, though.  Do you see this in your change?

**Comment by andrewh1978** [comment]
I'm not seeing the problem. How does the output differ for you?

**Comment by davepacheco** [comment]
Here's what I got, along with the diff from yours:
https://gist.github.com/davepacheco/737e13e820c91b42e8fe971292a55b6b

It looks one version of md2man-roff is escaping dashes while the other isn't.  Which version do you have?  I seem to have 2.0.0.

Both pages look fine using my man(1), so I'm not sure it makes any difference.  As long as you generated yours with md2man-roff, this may be a non-issue.

**Comment by andrewh1978** [comment]
I'm on 5.1.1. I did nothing unusual, just make manpages.

**Comment by davepacheco** [comment]
I upgraded my md2man and get the same result now.  Thanks for the patience.

I've integrated this change.  I hope you don't mind that I adjusted the commit message and CHANGES.md to match the existing convention.

This is the last change we'll do as a GitHub PR.  This repo has moved over to cr.joyent.us for review and integration.  I've updated the docs under #271.

**Pull request closed without merging**
