### PR TITLE
client.createReadStream should emit an 'open' event like fs.createReadStream

### PR DESCRIPTION
**Pull request by bahamas10**

### CODE REVIEW

**Comment by davepacheco** [comment]
This looks great!  Thoughts on adding a test case for it (or modifying the existing stream one to check this)?

**Comment by bahamas10** [comment]
tests added!

```
$ npm test

> manta@1.4.6 test /Users/dave/dev/node-manta
> nodeunit test/*.test.js


client.test.js
✔ mkdir
✔ mkdir (sub)
✔ put
✔ chattr
✔ put (zero byte streaming)
✔ put without mkdirp
✔ put with mkdirp
✔ streams
✔ put MD5 mismatch
✔ GH-72 content-length: undefined
✔ ls
✔ ln
✔ info (link)
✔ ftw
✔ create job (simple grep)
✔ get job
✔ add input keys
✔ get job input
✔ end job
✔ wait for job
✔ get job output
✔ create and cancel job
✔ unlink object
✔ unlink link
✔ rmr
✔ mkdirp/rmr
✔ GH-196 getPath ~~/
✔ #180: Invalid key results in no client error

OK: 87 assertions (21365ms)
```

**Comment by davepacheco** [comment]
Thanks!  I went to merge this, but it doesn't pass "make prepush":

    /Users/dap/work/node-manta/test/client.test.js(236): warning: identifer res hides an identifier in a parent scope

would you mind fixing that, and then collapsing all of the changes into one commit?  Thanks again.

**Comment by bahamas10** [comment]
ahh, didn't know about `prepush`

- `make prepush` works
- all commits squashed into one.

```
dave - manilla darwin ~/dev/node-manta (git:patch-1) $ make prepush
deps/javascriptlint/build/install/jsl --nologo --nosummary --conf=tools/jsl.node.conf lib/auth.js lib/client.js lib/create_client.js lib/index.js lib/jobshare.js lib/queue.js lib/string_stream.js test/client.test.js test/helper.js bin/mchattr bin/mchmod bin/mfind bin/mget bin/minfo bin/mjob bin/mln bin/mlogin bin/mls bin/mmd5 bin/mmkdir bin/mput bin/mrm bin/mrmdir bin/msign bin/muntar
/Users/dave/dev/node-manta/lib/auth.js
/Users/dave/dev/node-manta/lib/client.js
/Users/dave/dev/node-manta/lib/create_client.js
/Users/dave/dev/node-manta/lib/index.js
/Users/dave/dev/node-manta/lib/jobshare.js
/Users/dave/dev/node-manta/lib/queue.js
/Users/dave/dev/node-manta/lib/string_stream.js
/Users/dave/dev/node-manta/test/client.test.js
/Users/dave/dev/node-manta/test/helper.js
/Users/dave/dev/node-manta/bin/mchattr
/Users/dave/dev/node-manta/bin/mchmod
/Users/dave/dev/node-manta/bin/mfind
/Users/dave/dev/node-manta/bin/mget
/Users/dave/dev/node-manta/bin/minfo
/Users/dave/dev/node-manta/bin/mjob
/Users/dave/dev/node-manta/bin/mln
/Users/dave/dev/node-manta/bin/mlogin
/Users/dave/dev/node-manta/bin/mls
/Users/dave/dev/node-manta/bin/mmd5
/Users/dave/dev/node-manta/bin/mmkdir
/Users/dave/dev/node-manta/bin/mput
/Users/dave/dev/node-manta/bin/mrm
/Users/dave/dev/node-manta/bin/mrmdir
/Users/dave/dev/node-manta/bin/msign
/Users/dave/dev/node-manta/bin/muntar
deps/jsstyle/jsstyle -f tools/jsstyle.conf lib/auth.js lib/client.js lib/create_client.js lib/index.js lib/jobshare.js lib/queue.js lib/string_stream.js test/client.test.js test/helper.js bin/mchattr bin/mchmod bin/mfind bin/mget bin/minfo bin/mjob bin/mln bin/mlogin bin/mls bin/mmd5 bin/mmkdir bin/mput bin/mrm bin/mrmdir bin/msign bin/muntar
check ok
npm install
./node_modules/.bin/nodeunit test/*.test.js

client.test.js
✔ mkdir
✔ mkdir (sub)
✔ put
✔ chattr
✔ put (zero byte streaming)
✔ put without mkdirp
✔ put with mkdirp
✔ streams
✔ put MD5 mismatch
✔ GH-72 content-length: undefined
✔ ls
✔ ln
✔ info (link)
✔ ftw
✔ create job (simple grep)
✔ get job
✔ add input keys
✔ get job input
✔ end job
✔ wait for job
✔ get job output
✔ create and cancel job
✔ unlink object
✔ unlink link
✔ rmr
✔ mkdirp/rmr
✔ GH-196 getPath ~~/
✔ #180: Invalid key results in no client error

OK: 89 assertions (24751ms)
```

**Comment by davepacheco** [comment]
Thanks!

**Pull request merged**
