### PR TITLE
PUBAPI-1146 Divorce wanted between *_KEY_ID env vars and keyId actually sent to server

### PR DESCRIPTION
**Pull request by arekinath**
This updates `node-manta` to use the latest version of `smartdc-auth`, which has integrated all of the local improvements in our `auth.js`, as well as a number of useful changes from `node-smartdc` and others.

The original PR on smartdc-auth (https://github.com/joyent/node-smartdc-auth/pull/3) has a lot more information about exactly what has changed in this update.

Other than adding the new dependency, this patch removes the old `auth.js` file, the old dep on `ssh-agent`, and adds `manta: true` to the argument of all calls to `signUrl` -- this tells the now shared `signUrl` code to use Manta-style sub-users rather than SDC-style ones.

### CODE REVIEW

**Comment by arekinath** [comment]
https://github.com/arekinath/node-manta/commit/010825ef84e4d0219b467068cf1d9421eb2a7c61 is a diff between the old node-manta `auth.js` and its replacement in `smartdc-auth`, for inspecting the changes

**Comment by bahamas10** [comment]
Huge improvement... I'm a big fan of negative lines added.  I'll test in a bit and report back, but so far the code itself looks good... no obvious problems.

**Comment by bahamas10** [comment]
Tested against flat private key file and also ssh-agent and can confirm it works as expected.  LGTM

**Comment by arekinath** [comment]
diff updated to smartdc-auth 2.0.1, auth.js diff to https://github.com/arekinath/node-manta/commit/c70dea049cefc76be1108f63d82a7f5ef4eafd4d

**Comment by xer0x** [comment]
I should make a separate issue, however I tried out Alex's PR to see if it fixed an SSH error that I'm getting on OSX El Capitan. This didn't fix my problem.

```
mls /xer0x/stor
mls: Error: SHA256:MBcMbsS2QpZTxK23uWC5J111SfvnBtuYkvv/hygYtAQ not found in: /Users/drew/.ssh
```

**Comment by davepacheco** [comment]
I only took a quick skim of the gist diff.  Lines 252-265: I'm not sure how much this matters, but there's a race between checking and using here.  Also, what's the significance of 64K?  Should that be a constant like "MAX_KEY_LENGTH" or something?  Ditto in the "else" block here.

A few nits, up to you:

- KeyNotFoundError.join: maybe a comment explaining what this does?
- "manta": maybe "mantaStyleSubuser"?  I'm afraid calling it "manta" may make it tempting to overload it for unrelated changes.
- The comments at line 164 and lines 171-173 are not sentences.

My main question is just making sure that it's interface-compatible.  The node-manta client uses or exposes auth.signUrl, auth.cliSigner, auth.privateKeySigner, auth.sshAgentSigner, and auth.loadSSHKey, and it looks like those all at least exist.

**Comment by arekinath** [comment]
Updated, I've incorporated those comments. New fakediff is https://github.com/arekinath/node-manta/commit/6cc122ee027643de04378d2c81bb459c3793b74c?diff=split

**Comment by arekinath** [comment]
Merged as e5e6e75c3961c448523855fdb209cf79d56f8451

**Pull request closed without merging**
